version: '2.2'
services:
  web:
    restart: always
    image: 'nginx:${NGINX_VER:-1.23.2}-alpine'
    expose:
      - 8080
    environment:
      - MAGENTO_RUN_MODE=${MAGENTO_RUN_MODE:-developer}
      - MAGENTO_ROOT=${MAGENTO_ROOT:-/app}
      - DOCUMENT_ROOT=${DOCUMENT_ROOT:-/app/pub}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE:-128M}
    depends_on:
      - fpm_xdebug
    volumes:
      - '${SOURCE_PATH:-../html}:/app:ro'
      - '${FR_DOCKER_DEFAULT}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - '${FR_DOCKER_DEFAULT}/nginx/vhost.conf:/etc/nginx/templates/default.conf.template:ro'
      - '${FR_DOCKER_PROJECT}/nginx/custom.conf:/etc/nginx/conf.d/custom/custom.conf:ro'
  varnish:
    restart: always
    image: 'magento/magento-cloud-docker-varnish:${VARNISH_VER:-6.2}-1.2.2'
    environment:
      - VIRTUAL_HOST=${MAIN_DOMAIN},${MULTIPLE_DOMAINS}
      - VIRTUAL_PORT=80
      - CERT_NAME=${MAIN_DOMAIN}
    volumes:
      - '${FR_DOCKER_DEFAULT}/varnish/default.vcl:/etc/varnish/default.vcl'
    depends_on:
      - web
    networks:
      - default
      - proxy
networks:
  proxy:
    external: true
