version: '2.2'
services:
  web:
    restart: always
    image: 'bitnami/apache:${APACHE_VER:-2.4.46}-debian-10-r264'
    expose:
      - 8080
    environment:
      - DOCUMENT_ROOT=${DOCUMENT_ROOT:-/app/pub}
      - MAGENTO_ROOT=${MAGENTO_ROOT:-/app}
    depends_on:
      - fpm_xdebug
    volumes:
      - '${SOURCE_PATH:-../html}:/app:ro'
      - '${FR_DOCKER_DEFAULT}/apache/httpd.conf:/opt/bitnami/apache/conf/httpd.conf:ro'
      - '${FR_DOCKER_DEFAULT}/apache/vhost.conf:/opt/bitnami/apache/conf/vhosts/vhost.conf:ro'
      - '${FR_DOCKER_DEFAULT}/apache/pagespeed_${PAGESPEED:-off}.conf:/opt/bitnami/apache/conf/enable_pagespeed.conf:ro'
      - '${FR_DOCKER_PROJECT}/apache/custom.conf:/opt/bitnami/apache/conf/vhosts/custom/custom.conf:ro'
  varnish:
    restart: always
    image: 'magento/magento-cloud-docker-varnish:${VARNISH_VER:-6.2}-1.2.2'
    environment:
      - VIRTUAL_HOST=${MAIN_DOMAIN},${MULTIPLE_DOMAINS}
      - VIRTUAL_PORT=80
      - CERT_NAME=${MAIN_DOMAIN}
    volumes:
      - '${FR_DOCKER_DEFAULT}/varnish/default.vcl:/etc/default.vcl'
    depends_on:
      - web
    networks:
      - default
      - proxy
networks:
  proxy:
    external: true
