version: '2.2'
services:
  cloud:
    image: 'magento/magento-cloud-docker-php:${PHP_VER:-7.4}-cli${DOCKER_VER_TAG:1.3.2}'
    
    volumes:
      - '${SOURCE_PATH:-../html}:/app'
      - '~/.composer/cache:/root/.composer/cache:delegated'
      - '~/.ssh:/root/.ssh:delegated'
      - '~/.magento-cloud:/root/.magento-cloud'
      - ./cloud/install-command.sh:/install-command.sh
      - '/home/cuongho/.ssh/id_rsa.pub:/home/cuongho/.ssh/id_rsa.pub'
    #command: /bin/sh -c "/install-command.sh"
    entrypoint: [ "sh", "/install-command.sh" ]
    environment:
      - VIRTUAL_HOST=${MAIN_DOMAIN},${MULTIPLE_DOMAINS}
      - VIRTUAL_PORT=5000
      - CERT_NAME=${MAIN_DOMAIN}
      - DOCUMENT_ROOT=${DOCUMENT_ROOT:-/app/pub}
      - MAGENTO_RUN_MODE=${MAGENTO_RUN_MODE:-developer}
      - ENABLE_SENDMAIL=${ENABLE_SENDMAIL:-true}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE:-128M}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-4G}
      - "PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip redis xsl ${EXT_PHP_EXTENSION:-}"
