version: '2.2'
services:
  generic:
    image: alpine
    extra_hosts:
      - 'xdebug mailhog ${SHARED_SERVICES:-mysql redis elasticsearch mysql8}:${HOST_IP:-172.17.0.1}'
    environment:
      - DOCUMENT_ROOT=${DOCUMENT_ROOT:-/app/pub}
      - MAGENTO_RUN_MODE=${MAGENTO_RUN_MODE:-developer}
      - ENABLE_SENDMAIL=${ENABLE_SENDMAIL:-true}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE:-128M}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-4G}
      - "PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip redis xsl ${EXT_PHP_EXTENSION:-}"
    volumes:
      - '${SOURCE_PATH:-../html}:/app'
      - '${FR_DOCKER_DEFAULT}/php/ioncube/ioncube_loader_lin_${PHP_VER}.so:/usr/local/lib/php/extensions/ioncube.so'
      - '${FR_DOCKER_PROJECT}/php/php.ini:/usr/local/etc/php/conf.d/zzz-forix.ini'
      - '${FR_DOCKER_PROJECT}/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-forix.conf'
      - '${FR_DOCKER_PROJECT}/php/multisites.php:/multisites.php'
      - '${FR_DOCKER_SHARED}/certs/rootCA.pem:/usr/local/share/ca-certificates/rootCA.crt'
      - '${FR_DOCKER_DEFAULT}/custom-docker-entrypoint.sh:/root/custom-docker-entrypoint.sh'
  fpm:
    restart: always
    image: 'magento/magento-cloud-docker-php:${PHP_VER:-7.2}-fpm-${DOCKER_VER_TAG:-1.3.4}'
    command: ["php-fpm", "-R"]
    entrypoint: ["bash","/root/custom-docker-entrypoint.sh"]
    extends: generic
  fpm_xdebug:
    restart: always
    image: 'magento/magento-cloud-docker-php:${PHP_VER:-7.2}-fpm-${DOCKER_VER_TAG:-1.3.4}'
    extends: generic
    environment:
      - "PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip redis xsl xdebug ${EXT_PHP_EXTENSION:-}"
      - "PHP_IDE_CONFIG=serverName=${MAIN_DOMAIN}"
      - "XDEBUG_CONFIG=remote_host=xdebug"
  deploy:
    image: 'magento/magento-cloud-docker-php:${PHP_VER:-7.2}-cli-${DOCKER_VER_TAG:-1.3.4}'
    extends: generic
    volumes:
      - '~/.composer/cache:/root/.composer/cache:delegated'
      - '${FR_DOCKER_DEFAULT}/php/mnt:/mnt'
      - '${FR_DOCKER_DEFAULT}/php/tmp:/tmp'
    environment:
      - DEBUG=false
